apiVersion: v1
kind: Service
metadata:
  name: keer-adi-srav-service
  labels: 
    app: keer-adi-srav
spec:
  selector:
    app: keer-adi-srav
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
    name: http
    nodePort: 31416
  - port: 443
    protocol: TCP
    name: https
    